SELECT *
FROM "public".merge_split_storage('merge', '{3120,3124,3828}'::int[], '[{
   "identifier": "tatastore1013",
   "capacity_gb": 5000,
   "used_gb": 2000,
   "inheriting_parent": 3828,
   "storage_type": "SAN",
  "capacity_type": "Raw",
  "media_type": "SSD",
  "description": "hdkashdasdasd",
  "LUN": "adasd",
  "raid_level": "5",
  "pool": "sadsad",
  "label": "123123",
  "mean_disk_latency": 121,
  "mean_throughput": 1212,
  "mean_iops": 121,
  "access_frequency": "Low",
  "dns_name": "newname",
  "file_system": "1212",
  "used_for": "Database servers",
  "organization_id": "P125899"
 }]'::json);

SELECT *
FROM "public".merge_split_storage('split', '{561506}'::int[], '[{
   "identifier": "TimeoStorey23",
   "capacity_gb": 1000,
   "used_gb": 4000,
   "inheriting_parent": 561485,
   "storage_type": "SAN",
  "capacity_type": "Raw",
  "media_type": "SSD",
  "description": "hdkashdasdasd",
  "LUN": "adasd",
  "raid_level": "5",
  "pool": "sadsad",
  "label": "123123",
  "mean_disk_latency": 121,
  "mean_throughput": 1212,
  "mean_iops": 121,
  "access_frequency": "Low",
  "dns_name": "newname",
  "file_system": "1212",
  "used_for": "Database servers",
  "organization_id": "P125899"
 },{
   "identifier": "mero_store12412",
   "capacity_gb": 1000,
   "used_gb": 4000,
   "inheriting_parent": 561485,
   "storage_type": "SAN",
  "capacity_type": "Raw",
  "media_type": "SSD",
  "description": "hdkashdasdasd",
  "LUN": "adasd",
  "raid_level": "5",
  "pool": "sadsad",
  "label": "123123",
  "mean_disk_latency": 121,
  "mean_throughput": 1212,
  "mean_iops": 121,
  "access_frequency": "Low",
  "dns_name": "newname",
  "file_system": "1212",
  "used_for": "Database servers",
  "organization_id": "P125899"
 },{
   "identifier": "mero_store1423",
   "capacity_gb": 1000,
   "used_gb": 4000,
   "inheriting_parent": 561485,
   "storage_type": "SAN",
  "capacity_type": "Raw",
  "media_type": "SSD",
  "description": "hdkashdasdasd",
  "LUN": "adasd",
  "raid_level": "5",
  "pool": "sadsad",
  "label": "123123",
  "mean_disk_latency": 121,
  "mean_throughput": 1212,
  "mean_iops": 121,
  "access_frequency": "Low",
  "dns_name": "newname",
  "file_system": "1212",
  "used_for": "Database servers",
  "organization_id": "P125899"
 },{
   "identifier": "mero_store12414",
   "capacity_gb": 1000,
   "used_gb": 4000,
   "inheriting_parent": 561485,
   "storage_type": "SAN",
  "capacity_type": "Raw",
  "media_type": "SSD",
  "description": "hdkashdasdasd",
  "LUN": "adasd",
  "raid_level": "5",
  "pool": "sadsad",
  "label": "123123",
  "mean_disk_latency": 121,
  "mean_throughput": 1212,
  "mean_iops": 121,
  "access_frequency": "Low",
  "dns_name": "newname",
  "file_system": "1212",
  "used_for": "Database servers",
  "organization_id": "P125899"
 },{
   "identifier": "mero_store512412",
   "capacity_gb": 1000,
   "used_gb": 4000,
   "inheriting_parent": 561485,
   "storage_type": "SAN",
  "capacity_type": "Raw",
  "media_type": "SSD",
  "description": "hdkashdasdasd",
  "LUN": "adasd",
  "raid_level": "5",
  "pool": "sadsad",
  "label": "123123",
  "mean_disk_latency": 121,
  "mean_throughput": 1212,
  "mean_iops": 121,
  "access_frequency": "Low",
  "dns_name": "newname",
  "file_system": "1212",
  "used_for": "Database servers",
  "organization_id": "P125899"
 }]'::json);

-- WITH IDENTIFIER
